ADQUIRENTES_NETUNNA = {
    36: "Adiq",
    1: "Adyen",
    2: "Amex",
    40: "Alelo",
    3: "Bin",
    4: "Biq",
    5: "Calcard",
    41: "CashBerti",
    6: "Cielo",
    7: "ConductorPrivateLabel",
    37: "CooperCard",
    8: "CooperCred",
    9: "Elavon",
    10: "Facisc",
    11: "FitCard",
    12: "GetNet",
    13: "GlobalPayment",
    14: "Greencard",
    15: "Losango",
    16: "MettaCard",
    39: "Pagarme",
    38: "Pagseguro",
    17: "Personal",
    18: "RedeCard",
    35: "SafraPay",
    19: "Senff",
    20: "SinComercio",
    42: "Sicredi",
    21: "SiPag",
    22: "Sodexo",
    23: "Softnex",
    24: "Stone",
    25: "Ticket",
    26: "Telenet",
    27: "TicketLog",
    28: "Trio",
    34: "UtilCard",
    29: "Vale Card",
    30: "Vega",
    31: "Vero Banrisul",
    32: "Vero Cheque",
    33: "Vr"
}
